# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('plans', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
            preserve_default=False,
        ),
    ]
