import random
def genera_pass():
	lista_pass = [
        'orso', 
        'gatto',
        'cavallo', 
        'tigre', 
        'leone', 
        'scimmia', 
        'delfino',
        'lupo',
        'anatra',
        'pollo',
        'toro',
        'pesca',
        'melone',
        'mela',
        'fragola',
        'arancia',
        'kiwi',
        'estate',
        'inverno',
        'autunno',
        'primavera',
        'sole',
        'neve',
        'pioggia',
        'rosso',
        'verde',
        'giallo',
        'nero',
        'bianco',
        'senape',
        'calcio',
        'golf',
        'nuoto',
        'arpa',
        'flauto',
        'violino',
        'gennaio',
        'febbraio',
        'marzo',
        'aprile',
        'maggio',
        'giugno',
        'luglio',
        'agosto',
        'settembre',
        'ottobre',
        'novembre',
        'dicembre',
        'penna',
        'matita',
        'muro'
    ]

	passw  = random.choice(lista_pass)+str(random.randint(1000, 9999))
	return passw
